theme: jekyll-theme-cayman
title: Dash
description: Website for Dash interface for Windows 10.
plugins:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-seo-tag
   - jekyll-include-cache
   - jekyll-relative-links